### ISSUE TITLE
Bug in MGmol::write_hdf5?

### ISSUE THREAD

**Issue by Rombur** [llnl/mgmol#77]
[Here](https://github.com/LLNL/mgmol/blob/release/src/restart.cc#L71-L89) the function takes a `LocalizationRegions` as an argument but it is not used. Instead, we use the private variable. Is the argument useless or should we use it instead of the private variable?

**Comment by jeanlucf22** [comment]
I would say preserve current functionality and remove unused argument.
I believe it doesn't matter at teh moment since all calls to that function seem to pass the same object: MGmol::lrs_
But removing the unused argument will clarify code.

**Comment by Rombur** [comment]
Fixed in #76
